/** * LOGISTIC PRO - ПОВНА БАЗА (ОНОВЛЕНО З НОВИМИ ТАРИФАМИ ТА ПОРТАМИ)
 * Оновлено: Березень 2026
 */
const db = {
  "copart": {
    "- Illinois - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "ABILENE - Texas - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Houston" },
    "ADELANTO - California - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Los Angeles" },
    "ADP TOWING MAUI - Hawaii - Copart": { "Car": 2400, "SUV": 2400, "Motorcycle": 2400, "Pickup": 2600, "port": "Los Angeles" },
    "AKRON - Ohio - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "ALBANY - New York - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "New York" },
    "ALBUQUERQUE - New Mexico - Copart": { "Car": 750, "SUV": 750, "Motorcycle": 750, "Pickup": 950, "port": "Houston" },
    "ALTOONA - Pennsylvania - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "AMARILLO - Texas - Copart": { "Car": 675, "SUV": 675, "Motorcycle": 675, "Pickup": 875, "port": "Houston" },
    "ANCHORAGE - Alaska - Copart": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Anchorage" },
    "ANDREWS - Texas - Copart": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Houston" },
    "ANTELOPE - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "APPLETON - Wisconsin - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Chicago" },
    "ATLANTA EAST - Georgia - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "ATLANTA NORTH - Georgia - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Savannah" },
    "ATLANTA SOUTH - Georgia - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "ATLANTA WEST - Georgia - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "AUSTIN - Texas - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Houston" },
    "Augusta - Georgia - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "BAKERSFIELD - California - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Los Angeles" },
    "BALTIMORE - Maryland - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Norfolk" },
    "BALTIMORE EAST - Maryland - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Norfolk" },
    "BATON ROUGE - Louisiana - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Houston" },
    "BILLINGS - Montana - Copart": { "Car": 1000, "SUV": 1000, "Motorcycle": 1000, "Pickup": 1200, "port": "Seattle" },
    "BIRMINGHAM - Alabama - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Savannah" },
    "BISMARCK - North Dakota - Copart": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "BOISE - Idaho - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Seattle" },
    "Buffalo - New York - Copart": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "New York" },
    "CALGARY - Alberta - Copart": { "Car": 1600, "SUV": 1600, "Motorcycle": 1600, "Pickup": 1800, "port": "Toronto" },
    "CANDIA - New Hampshire - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "New York" },
    "CARTERSVILLE - Georgia - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "CASPER - Wyoming - Copart": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "CASPER WEST - Wyoming - Copart": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "CEDAR RAPIDS - Iowa - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "CHAMBERSBURG - Pennsylvania - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "New York" },
    "CHARLESTON - West Virginia - Copart": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Norfolk" },
    "CHICAGO NORTH - Illinois - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "CHICAGO SOUTH - Illinois - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "CHINA GROVE - North Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "CICERO - Indiana - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "CLEVELAND EAST - Ohio - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "CLEVELAND WEST - Ohio - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "CLEWISTON - Florida - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Miami" },
    "COLORADO SPRINGS - Colorado - Copart": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "COLUMBUS - Ohio - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "CONCORD - North Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "CORPUS CHRISTI - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "CRASHEDTOYS ATLANTA - Georgia - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "CRASHEDTOYS DALLAS - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "CRASHEDTOYS SACRAMENTO - California - Copart": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Los Angeles" },
    "DALLAS - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "DALLAS SOUTH - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "DANVILLE - Virginia - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "DAVENPORT - 169 Davenport sublot - Iowa - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Chicago" },
    "DAVENPORT - Iowa - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Chicago" },
    "DAYTON - Ohio - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "DENVER - Colorado - Copart": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "DENVER CENTRAL - Colorado - Copart": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "DENVER SOUTH - Colorado - Copart": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "DES MOINES - Iowa - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "DETROIT - Michigan - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "DOTHAN - Alabama - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Savannah" },
    "DYER - Indiana - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "Dyer Auto Auction - Indiana - Dyer Auto Auction": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "EARLINGTON - Kentucky - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "EDMONTON - Alberta - Copart": { "Car": 1600, "SUV": 1600, "Motorcycle": 1600, "Pickup": 1800, "port": "Toronto" },
    "EL PASO - Texas - Copart": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Houston" },
    "EUGENE - Oregon - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Seattle" },
    "EXETER - Rhode Island - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "New York" },
    "FAIRBURN - Georgia - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "FAYETTEVILLE - Arkansas - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "FLINT - Michigan - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "FORT WAYNE - Indiana - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "FREDERICKSBURG - Virginia - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Norfolk" },
    "FREETOWN - Massachusetts - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "FRESNO - California - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Los Angeles" },
    "FT. PIERCE - Florida - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Miami" },
    "FT. WORTH - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "GASTONIA - North Carolina - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Norfolk" },
    "GLASSBORO EAST - New Jersey - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "GLASSBORO WEST - New Jersey - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "GRAHAM - Washington - Copart": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Seattle" },
    "Grenada - Mississippi - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "HALIFAX - Nova Scotia - Copart": { "Car": 1350, "SUV": 1350, "Motorcycle": 1350, "Pickup": 1550, "port": "Toronto" },
    "HAMPTON - Virginia - Copart": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Norfolk" },
    "HARRISBURG - Pennsylvania - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 375, "Pickup": 625, "port": "New York" },
    "HARTFORD - Connecticut - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "New York" },
    "HARTFORD SPRINGFIELD - Connecticut - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "HAYWARD - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "HELENA - Montana - Copart": { "Car": 900, "SUV": 900, "Motorcycle": 900, "Pickup": 1100, "port": "Seattle" },
    "HONOLULU - Hawaii - Copart": { "Car": 270, "SUV": 270, "Motorcycle": 270, "Pickup": 470, "port": "Honolulu" },
    "HOUSTON - Texas - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Houston" },
    "HOUSTON EAST - Texas - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Houston" },
    "INDIANAPOLIS - Indiana - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "IONIA - Michigan - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "Illinois - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "JACKSON - Mississippi - Copart": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Houston" },
    "JACKSONVILLE EAST - Florida - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Savannah" },
    "JACKSONVILLE NORTH - Florida - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Savannah" },
    "JACKSONVILLE WEST - Florida - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Savannah" },
    "KANSAS CITY - Kansas - Copart": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Savannah" },
    "KENS TOWING HILO - Hawaii - Copart": { "Car": 2250, "SUV": 2250, "Motorcycle": 2250, "Pickup": 2450, "port": "Los Angeles" },
    "KINCHELOE - Michigan - Copart": { "Car": 900, "SUV": 900, "Motorcycle": 900, "Pickup": 1100, "port": "Chicago" },
    "KINDAQUICK TOWING LLC - Hawaii - Copart": { "Car": 2900, "SUV": 2900, "Motorcycle": "Call", "Pickup": 3100, "port": "Los Angeles" },
    "KNOXVILLE - Tennessee - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "LANSING - Michigan - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "LAS VEGAS - Nevada - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Los Angeles" },
    "LAS VEGAS WEST - Nevada - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Los Angeles" },
    "LEXINGTON EAST - Kentucky - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "LEXINGTON WEST - Kentucky - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "LINCOLN - Nebraska - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "LITTLE ROCK - Arkansas - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Houston" },
    "LONDON - Ontario - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Toronto" },
    "LONG BEACH - California - Copart": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Los Angeles" },
    "LONG ISLAND - New York - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "LONGVIEW - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "LOS ANGELES - California - Copart": { "Car": 310, "SUV": 310, "Motorcycle": 310, "Pickup": 510, "port": "Los Angeles" },
    "LOUISVILLE - Kentucky - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "LUFKIN - Texas - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "LUMBERTON - North Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "LYMAN - Maine - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "New York" },
    "MACON - Georgia - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Savannah" },
    "MADISON - Wisconsin - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "MADISON SOUTH - Wisconsin - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "MARTINEZ - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "MCALLEN - Texas - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Houston" },
    "MEBANE - North Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "MEMPHIS - Tennessee - Copart": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "Savannah" },
    "MENTONE - California - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Los Angeles" },
    "MIAMI CENTRAL - Florida - Copart": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "Miami" },
    "MIAMI NORTH - Florida - Copart": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "Miami" },
    "MIAMI SOUTH - Florida - Copart": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Miami" },
    "MILWAUKEE - Wisconsin - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Chicago" },
    "MILWAUKEE NORTH - Wisconsin - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Chicago" },
    "MILWAUKEE SOUTH - Wisconsin - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Chicago" },
    "MINNEAPOLIS - Minnesota - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "MINNEAPOLIS NORTH - Minnesota - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "MO - COLUMBIA - Missouri - Copart": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Savannah" },
    "MOBILE - Alabama - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "MOBILE SOUTH - Alabama - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "MOCKSVILLE - North Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "MONCTON - New Brunswick - Copart": { "Car": 1425, "SUV": 1425, "Motorcycle": 1425, "Pickup": 1625, "port": "Toronto" },
    "MONTGOMERY - Alabama - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "MONTREAL - Quebec - Copart": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "Toronto" },
    "N.Boston-ROWLEY Sublot - Massachusetts - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "NAPA - California - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Los Angeles" },
    "NASHVILLE - Tennessee - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "NEW ORLEANS - Louisiana - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Houston" },
    "NEWBURGH - New York - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "New York" },
    "NORTH AUSTIN - Texas - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Houston" },
    "NORTH BOSTON - Massachusetts - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "NORTH CHARLESTON - South Carolina - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "NORTH SEATTLE - Washington - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Seattle" },
    "OCALA - Florida - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Miami" },
    "OGDEN - Utah - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Los Angeles" },
    "OKLAHOMA CITY - Oklahoma - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Houston" },
    "ORLANDO - Florida - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "ORLANDO NORTH - Florida - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "ORLANDO SOUTH - Florida - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "OTTAWA - Ontario - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Toronto" },
    "PASCO - Washington - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Seattle" },
    "PEORIA - Illinois - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "PHILADELPHIA - Pennsylvania - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "PHILADELPHIA EAST-SUBLOT - Pennsylvania - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "PHOENIX - Arizona - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Los Angeles" },
    "PITTSBURGH EAST - Pennsylvania - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "New York" },
    "PITTSBURGH NORTH - Pennsylvania - Copart": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Norfolk" },
    "PITTSBURGH SOUTH - Pennsylvania - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 475, "Pickup": 800, "port": "New York" },
    "PITTSBURGH WEST - Pennsylvania - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "PORTLAND NORTH - Oregon - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Seattle" },
    "PORTLAND SOUTH - Oregon - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Seattle" },
    "PUNTA GORDA - Florida - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Miami" },
    "PUNTA GORDA SOUTH - Florida - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Miami" },
    "Phoenix North - Arizona - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Los Angeles" },
    "RALEIGH - North Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "RANCHO CUCAMONGA - California - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "RAPID CITY - South Dakota - Copart": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "REDDING - California - Copart": { "Car": 950, "SUV": 950, "Motorcycle": 950, "Pickup": 1150, "port": "Los Angeles" },
    "RENO - Nevada - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Los Angeles" },
    "RICHMOND - Virginia - Copart": { "Car": 325, "SUV": 325, "Motorcycle": 325, "Pickup": 525, "port": "Norfolk" },
    "RICHMOND EAST - Virginia - Copart": { "Car": 325, "SUV": 325, "Motorcycle": 325, "Pickup": 525, "port": "Norfolk" },
    "ROCHESTER - New York - Copart": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "RUTLAND - Vermont - Copart": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "New York" },
    "SACRAMENTO - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "SALT LAKE CITY - Utah - Copart": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Los Angeles" },
    "SALT LAKE CITY NORTH - Utah - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Los Angeles" },
    "SAN ANTONIO - Texas - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Houston" },
    "SAN BERNARDINO - California - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "SAN DIEGO - California - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Los Angeles" },
    "SAN JOSE - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "SAVANNAH - Georgia - Copart": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "Savannah" },
    "SAVANNAH / VERTIA SUBLOT-Georgia Copart - Georgia - Copart": { "Car": 325, "SUV": 325, "Motorcycle": 325, "Pickup": 525, "port": "Savannah" },
    "SC - COLUMBIA - South Carolina - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "SCRANTON - Pennsylvania - Copart": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "SEAFORD - Delaware - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "New York" },
    "SHREVEPORT - Louisiana - Copart": { "Car": 465, "SUV": 465, "Motorcycle": 465, "Pickup": 665, "port": "Houston" },
    "SIKESTON - Missouri - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Chicago" },
    "SO SACRAMENTO - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "SOMERVILLE - New Jersey - Copart": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "New York" },
    "SOUTH BOSTON - Massachusetts - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "SPARTANBURG - South Carolina - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "SPOKANE - Washington - Copart": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Seattle" },
    "SPRINGFIELD - Missouri - Copart": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Savannah" },
    "ST. CLOUD - Minnesota - Copart": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "Chicago" },
    "ST. JOHN'S - Newfoundland and Lab - Copart": { "Car": 2000, "SUV": 2000, "Motorcycle": 2000, "Pickup": 2200, "port": "Toronto" },
    "ST. LOUIS - Missouri - Copart": { "Car": 725, "SUV": 725, "Motorcycle": 725, "Pickup": 925, "port": "Savannah" },
    "SUN VALLEY - California - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "SYRACUSE - New York - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "New York" },
    "Southern Illinois - Illinois - Copart": { "Car": 725, "SUV": 725, "Motorcycle": 725, "Pickup": 925, "port": "Savannah" },
    "TALLAHASSEE - Florida - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Savannah" },
    "TAMPA SOUTH - Florida - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Miami" },
    "TAMPA SOUTH - Mulberry Sublot - Florida - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Miami" },
    "TANNER - Alabama - Copart": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Savannah" },
    "TIFTON - Georgia - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "TORONTO - Ontario - Copart": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Toronto" },
    "TOW GUYS KAMUELA - Hawaii - Copart": { "Car": 2450, "SUV": 2450, "Motorcycle": 2450, "Pickup": 2650, "port": "Los Angeles" },
    "TRENTON - New Jersey - Copart": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "New York" },
    "TUCSON - Arizona - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "TULSA - Oklahoma - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "VALLEJO - California - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "VAN NUYS - California - Copart": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "WACO - Texas - Copart": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Houston" },
    "WALTON - Kentucky - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "WASHINGTON DC - Maryland - Copart": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "WAYLAND - Michigan - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "WEBSTER - New Hampshire - Copart": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "New York" },
    "WEST PALM BEACH - Florida - Copart": { "Car": 320, "SUV": 320, "Motorcycle": 320, "Pickup": 520, "port": "Miami" },
    "WEST WARREN - Massachusetts - Copart": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "WHEELING - Illinois - Copart": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "WICHITA - Kansas - Copart": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Houston" },
    "Windham - Maine - Copart": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "New York" },
    "YORK HAVEN - Pennsylvania - Copart": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "New York" }
  },
  "iaai": {
    "ABILENE - Texas - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Houston" },
    "ACE - Carson - California - IAAI": { "Car": 310, "SUV": 310, "Motorcycle": 310, "Pickup": 510, "port": "Los Angeles" },
    "ACE - PERRIS 2 - California - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Los Angeles" },
    "ACE - Perris - California - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Los Angeles" },
    "AKRON-CANTON - Ohio - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "ALBANY - New York - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "New York" },
    "ALBUQUERQUE - New Mexico - IAAI": { "Car": 750, "SUV": 750, "Motorcycle": 750, "Pickup": 950, "port": "Houston" },
    "ALTOONA - Pennsylvania - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "AMARILLO - Texas - IAAI": { "Car": 675, "SUV": 675, "Motorcycle": 675, "Pickup": 875, "port": "Houston" },
    "ANAHEIM - California - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "ANCHORAGE - Alaska - IAAI": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Anchorage" },
    "APPLETON - Wisconsin - IAAI": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Chicago" },
    "ASHEVILLE - North Carolina - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Norfolk" },
    "ASHLAND - Kentucky - IAAI": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "ATLANTA - Georgia - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "ATLANTA EAST - Georgia - IAAI": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Savannah" },
    "ATLANTA NORTH - Georgia - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "ATLANTA SOUTH - Georgia - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "AUSTIN - Texas - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Houston" },
    "AUSTIN NORTH - Texas - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "AVENEL NEW JERSEY - New Jersey - IAAI": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "New York" },
    "Atlanta West - Georgia - IAAI": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Savannah" },
    "BALTIMORE - Maryland - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Norfolk" },
    "BATON ROUGE - Louisiana - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Houston" },
    "BILLINGS - Montana - IAAI": { "Car": 1000, "SUV": 1000, "Motorcycle": 1000, "Pickup": 1200, "port": "Seattle" },
    "BIRMINGHAM - Alabama - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Savannah" },
    "BOISE - Idaho - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Seattle" },
    "BOSTON - SHIRLEY - Massachusetts - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "BOWLING GREEN - Kentucky - IAAI": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "BRIDGEPORT - Pennsylvania - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "BUCKHANNON - West Virginia - IAAI": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Norfolk" },
    "BUFFALO - New York - IAAI": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "New York" },
    "BURLINGTON - Vermont - IAAI": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "New York" },
    "BZ Trucking - Hawaii - IAAI": { "Car": 2450, "SUV": 2450, "Motorcycle": 2450, "Pickup": 2650, "port": "Los Angeles" },
    "CASPER - Wyoming - IAAI": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "CENTRAL NEW JERSEY - New Jersey - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "New York" },
    "CHARLESTON - South Carolina - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "CHARLOTTE - North Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "CHATTANOOGA - Tennessee - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Savannah" },
    "CHICAGO-NORTH - Illinois - IAAI": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "CHICAGO-SOUTH - Illinois - IAAI": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "CHICAGO-WEST - Illinois - IAAI": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Chicago" },
    "CINCINNATI - Ohio - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "CINCINNATI SOUTH - Ohio - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "CLEARWATER - Florida - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "CLEVELAND - Ohio - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "COLTON - California - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "COLUMBIA - South Carolina - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "COLUMBUS - Ohio - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "CONCORD - North Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "CORPUS CHRISTI - Texas - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "CULPEPER - Virginia - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Norfolk" },
    "Colorado Springs - Colorado - IAAI": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "D&D TOWING INC MAUI - Hawaii - IAAI": { "Car": 2550, "SUV": 2550, "Motorcycle": 2550, "Pickup": 2750, "port": "Los Angeles" },
    "DALLAS - Texas - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "DAVENPORT - Iowa - IAAI": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Chicago" },
    "DAYTON - Ohio - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Norfolk" },
    "DC TOWING HILO - Hawaii - IAAI": { "Car": 2250, "SUV": 2250, "Motorcycle": 2250, "Pickup": 2450, "port": "Los Angeles" },
    "DENVER - Colorado - IAAI": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "DENVER EAST - Colorado - IAAI": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "DES MOINES - Iowa - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "DETROIT - Michigan - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "DOTHAN - Alabama - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Savannah" },
    "DUNDALK - Maryland - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "Dallas/Ft Worth - Texas - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "EAST BAY - California - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "EL PASO - Texas - IAAI": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Houston" },
    "ERIE - Pennsylvania - IAAI": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "New York" },
    "EUGENE - Oregon - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Seattle" },
    "Elkton - Maryland - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Norfolk" },
    "Englishtown - New Jersey - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "New York" },
    "FARGO - North Dakota - IAAI": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "FAYETTEVILLE - Arkansas - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "FLINT - Michigan - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "FONTANA - California - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "FORT MYERS - Florida - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "FORT PIERCE - Florida - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Miami" },
    "FREMONT - California - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "FRESNO - California - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Los Angeles" },
    "Fort Wayne - Indiana - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "Fort Worth North - Texas - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "Fredericksburg-South - Virginia - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Norfolk" },
    "GRAND RAPIDS - Michigan - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Chicago" },
    "GREENSBORO - North Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "GREENVILLE - South Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "GRENADA - Mississippi - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "GULF COAST - Mississippi - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "HARTFORD - Connecticut - IAAI": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "New York" },
    "HARTFORD-SOUTH - Connecticut - IAAI": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "New York" },
    "HIGH DESERT - California - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Los Angeles" },
    "HIGH POINT - North Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "HONOLULU - Hawaii - IAAI": { "Car": 270, "SUV": 270, "Motorcycle": 270, "Pickup": 470, "port": "Honolulu" },
    "HOUSTON - Texas - IAAI": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Houston" },
    "HOUSTON SOUTH - Texas - IAAI": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Houston" },
    "HOUSTON-NORTH - Texas - IAAI": { "Car": 315, "SUV": 315, "Motorcycle": 315, "Pickup": 515, "port": "Houston" },
    "HUNTSVILLE - Alabama - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Savannah" },
    "INDIANAPOLIS - Indiana - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "Indianapolis South - Indiana - IAAI": { "Car": 750, "SUV": 750, "Motorcycle": 750, "Pickup": 950, "port": "Savannah" },
    "JACKSON - Mississippi - IAAI": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Houston" },
    "JACKSONVILLE - Florida - IAAI": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Savannah" },
    "KANSAS CITY - Kansas - IAAI": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Savannah" },
    "KNOXVILLE - Tennessee - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "Kansas City East - Missouri - IAAI": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Savannah" },
    "LAFAYETTE - Louisiana - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Houston" },
    "LAKE CITY - Georgia - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "LAS VEGAS - (OLD) - Nevada - IAAI": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "Los Angeles" },
    "LAS VEGAS - Nevada - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Los Angeles" },
    "LAUREL - Maryland - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "LEE'S TOWING KAUAI - Hawaii - IAAI": { "Car": 2900, "SUV": 2900, "Motorcycle": "Call", "Pickup": 3100, "port": "Los Angeles" },
    "LINCOLN - Illinois - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "LITTLE ROCK - Arkansas - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Houston" },
    "LONG ISLAND - New York - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "LONGVIEW - Texas - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Houston" },
    "LOS ANGELES - California - IAAI": { "Car": 310, "SUV": 310, "Motorcycle": 310, "Pickup": 510, "port": "Los Angeles" },
    "LOUISVILLE - Kentucky - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "LOUISVILLE NORTH - Kentucky - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Savannah" },
    "LUBBOCK - Texas - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Houston" },
    "Lexington - South Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Savannah" },
    "Los Angeles South - California - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Los Angeles" },
    "MACON - Georgia - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "MANCHESTER - New Hampshire - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "New York" },
    "MCALLEN - Texas - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Houston" },
    "MEMPHIS - Tennessee - IAAI": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "Savannah" },
    "METRO DC - Maryland - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "MIAMI - Florida - IAAI": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "Miami" },
    "MIAMI-NORTH - Florida - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Miami" },
    "MILWAUKEE - Wisconsin - IAAI": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Chicago" },
    "MINNEAPOLIS/ST. PAUL - Minnesota - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "MISSOULA - Montana - IAAI": { "Car": 750, "SUV": 750, "Motorcycle": 750, "Pickup": 950, "port": "Seattle" },
    "Minneapolis South - Minnesota - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "Monticello - New York - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "NASHVILLE - Tennessee - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Savannah" },
    "NEW CASTLE - Delaware - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "NEW ORLEANS - Louisiana - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Houston" },
    "NEW ORLEANS EAST - Louisiana - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Houston" },
    "NEWBURGH - New York - IAAI": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "New York" },
    "NORTH HOLLYWOOD - California - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Los Angeles" },
    "NORTHERN NEW JERSEY - New Jersey - IAAI": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "New York" },
    "NORTHERN VIRGINIA - Virginia - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Norfolk" },
    "New Orleans and Louisiana Flood - Louisiana - IAAI": { "Car": 575, "SUV": 575, "Motorcycle": 575, "Pickup": 775, "port": "Savannah" },
    "OKLAHOMA CITY - Oklahoma - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Houston" },
    "OMAHA - Nebraska - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "ORLANDO - Florida - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "ORLANDO-NORTH - Florida - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "Omaha South - Nebraska - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Chicago" },
    "PADUCAH - Kentucky - IAAI": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "PENSACOLA - Florida - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Miami" },
    "PERMIAN BASIN - Texas - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "Houston" },
    "PHILADELPHIA - Pennsylvania - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "PHOENIX - Arizona - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Los Angeles" },
    "PITTSBURGH - Pennsylvania - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "PITTSBURGH-NORTH - Pennsylvania - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "PORT MURRAY - New Jersey - IAAI": { "Car": 325, "SUV": 325, "Motorcycle": 325, "Pickup": 525, "port": "New York" },
    "PORTAGE - Wisconsin - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Chicago" },
    "PORTLAND - GORHAM - Maine - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "New York" },
    "PORTLAND - Oregon - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Seattle" },
    "PORTLAND SOUTH - Oregon - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Seattle" },
    "PROVIDENCE - Rhode Island - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "New York" },
    "PULASKI - Virginia - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Norfolk" },
    "Philadelphia East - Pennsylvania - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "Portland West - Oregon - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Seattle" },
    "Provo - Utah - IAAI": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Los Angeles" },
    "RALEIGH - North Carolina - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Norfolk" },
    "RENO - Nevada - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Los Angeles" },
    "RICHMOND - Virginia - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "Norfolk" },
    "ROANOKE - Virginia - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Norfolk" },
    "ROCHESTER - New York - IAAI": { "Car": 600, "SUV": 600, "Motorcycle": 600, "Pickup": 800, "port": "New York" },
    "ROSEDALE - Maryland - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Norfolk" },
    "SACRAMENTO - California - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "SACRAMENTO WEST - California - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Los Angeles" },
    "SALT LAKE CITY - Utah - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Los Angeles" },
    "SAN ANTONIO - Texas - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Houston" },
    "SAN ANTONIO-SOUTH - Texas - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Houston" },
    "SAN BERNARDINO - California - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Los Angeles" },
    "SAN DIEGO - California - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Los Angeles" },
    "SANTA CLARITA - California - IAAI": { "Car": 450, "SUV": 450, "Motorcycle": 450, "Pickup": 650, "port": "Los Angeles" },
    "SAVANNAH - Georgia - IAAI": { "Car": 275, "SUV": 275, "Motorcycle": 275, "Pickup": 475, "port": "Savannah" },
    "SCRANTON - Pennsylvania - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "New York" },
    "SEATTLE - Washington - IAAI": { "Car": 325, "SUV": 325, "Motorcycle": 325, "Pickup": 525, "port": "Seattle" },
    "SHADY SPRING - West Virginia - IAAI": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Norfolk" },
    "SHREVEPORT - Louisiana - IAAI": { "Car": 465, "SUV": 465, "Motorcycle": 465, "Pickup": 665, "port": "Houston" },
    "SIOUX FALLS - South Dakota - IAAI": { "Car": 800, "SUV": 800, "Motorcycle": 800, "Pickup": 1000, "port": "Chicago" },
    "SOUTH BEND - Indiana - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Chicago" },
    "SOUTHERN NEW JERSEY - New Jersey - IAAI": { "Car": 350, "SUV": 350, "Motorcycle": 350, "Pickup": 550, "port": "New York" },
    "SPOKANE - Washington - IAAI": { "Car": 500, "SUV": 500, "Motorcycle": 500, "Pickup": 700, "port": "Seattle" },
    "SPRINGFIELD - Missouri - IAAI": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Savannah" },
    "ST. CLOUD - Minnesota - IAAI": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "Chicago" },
    "ST. LOUIS - Illinois - IAAI": { "Car": 725, "SUV": 725, "Motorcycle": 725, "Pickup": 925, "port": "Savannah" },
    "STOCKTON - California - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Los Angeles" },
    "SYRACUSE - New York - IAAI": { "Car": 475, "SUV": 475, "Motorcycle": 475, "Pickup": 675, "port": "New York" },
    "Sayreville - New Jersey - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "New York" },
    "Suffolk - Virginia - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Norfolk" },
    "TAMPA - Florida - IAAI": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Miami" },
    "TAUNTON - Massachusetts - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "TIDEWATER - Virginia - IAAI": { "Car": 300, "SUV": 300, "Motorcycle": 300, "Pickup": 500, "port": "Norfolk" },
    "TIFTON - Georgia - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Savannah" },
    "TUCSON - Arizona - IAAI": { "Car": 550, "SUV": 550, "Motorcycle": 550, "Pickup": 750, "port": "Los Angeles" },
    "TULSA - Oklahoma - IAAI": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Houston" },
    "Tampa North - Florida - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "Miami" },
    "Templeton - Massachusetts - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "New York" },
    "WEST PALM BEACH - Florida - IAAI": { "Car": 330, "SUV": 330, "Motorcycle": 330, "Pickup": 530, "port": "Miami" },
    "WESTERN COLORADO - Colorado - IAAI": { "Car": "Call", "SUV": "Call", "Motorcycle": "Call", "Pickup": "Call", "port": "Chicago" },
    "WICHITA - Kansas - IAAI": { "Car": 700, "SUV": 700, "Motorcycle": 700, "Pickup": 900, "port": "Houston" },
    "WILMINGTON - North Carolina - IAAI": { "Car": 525, "SUV": 525, "Motorcycle": 525, "Pickup": 725, "port": "Norfolk" },
    "YORK SPRINGS - Pennsylvania - IAAI": { "Car": 425, "SUV": 425, "Motorcycle": 425, "Pickup": 625, "port": "New York" }
  },
  "canada": {
    "Calgary North - Alberta - Impact Auto Auctions": { "Car": 1600, "SUV": 1600, "Motorcycle": 1600, "Pickup": 1800, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" },
    "Calgary South - Alberta - Impact Auto Auctions": { "Car": 1600, "SUV": 1600, "Motorcycle": 1600, "Pickup": 1800, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" },
    "Edmonton - Alberta - Impact Auto Auctions": { "Car": 1600, "SUV": 1600, "Motorcycle": 1600, "Pickup": 1800, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" },
    "Halifax - Nova Scotia - Impact Auto Auctions": { "Car": 1350, "SUV": 1350, "Motorcycle": 1350, "Pickup": 1550, "port": "Toronto", "tax": 0.15, "taxName": "HST 15%" },
    "Hamilton - Ontario - Impact Auto Auctions": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Toronto", "tax": 0.13, "taxName": "HST 13%" },
    "London - Ontario - Impact Auto Auctions": { "Car": 400, "SUV": 400, "Motorcycle": 400, "Pickup": 600, "port": "Toronto", "tax": 0.13, "taxName": "HST 13%" },
    "Moncton - New Brunswick - Impact Auto Auctions": { "Car": 1425, "SUV": 1425, "Motorcycle": 1425, "Pickup": 1625, "port": "Toronto", "tax": 0.15, "taxName": "HST 15%" },
    "Montreal - Quebec - Impact Auto Auctions": { "Car": 650, "SUV": 650, "Motorcycle": 650, "Pickup": 850, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" },
    "Ottawa - Ontario - Impact Auto Auctions": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Toronto", "tax": 0.13, "taxName": "HST 13%" },
    "Québec City - Quebec - Impact Auto Auctions": { "Car": 775, "SUV": 775, "Motorcycle": 775, "Pickup": 975, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" },
    "St. John's - Newfoundland and Lab - Impact Auto Auctions": { "Car": 2000, "SUV": 2000, "Motorcycle": 2000, "Pickup": 2200, "port": "Toronto", "tax": 0.15, "taxName": "HST 15%" },
    "Sudbury - Ontario - Impact Auto Auctions": { "Car": 625, "SUV": 625, "Motorcycle": 625, "Pickup": 825, "port": "Toronto", "tax": 0.13, "taxName": "HST 13%" },
    "Toronto - Ontario - Impact Auto Auctions": { "Car": 375, "SUV": 375, "Motorcycle": 375, "Pickup": 575, "port": "Toronto", "tax": 0.13, "taxName": "HST 13%" },
    "Vancouver - British Columbia - Impact Auto Auctions": { "Car": 2100, "SUV": 2100, "Motorcycle": 2100, "Pickup": 2300, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" },
    "Winnipeg - Manitoba - Impact Auto Auctions": { "Car": 1450, "SUV": 1450, "Motorcycle": 1450, "Pickup": 1650, "port": "Toronto", "tax": 0.05, "taxName": "GST 5%" }
  }
};

const seaRates = {
  "New York": { "end": "Klaipeda", "Car": 700, "SUV": 700, "Pickup": 1000, "Motorcycle": 400 },
  "Newark": { "end": "Klaipeda", "Car": 700, "SUV": 700, "Pickup": 1000, "Motorcycle": 400 },
  "Norfolk": { "end": "Klaipeda", "Car": 675, "SUV": 675, "Pickup": 975, "Motorcycle": 400 },
  "Savannah": { "end": "Klaipeda", "Car": 675, "SUV": 675, "Pickup": 975, "Motorcycle": 400 },
  "Miami": { "end": "Klaipeda", "Car": 750, "SUV": 750, "Pickup": 1050, "Motorcycle": 425 },
  "Houston": { "end": "Klaipeda", "Car": 750, "SUV": 750, "Pickup": 1100, "Motorcycle": 425 },
  "Chicago": { "end": "Klaipeda", "Car": 850, "SUV": 850, "Pickup": 1250, "Motorcycle": 450 },
  "Los Angeles": { "end": "Klaipeda", "Car": 1225, "SUV": 1225, "Pickup": 1700, "Motorcycle": 600 },
  "Seattle": { "end": "Klaipeda", "Car": 1625, "SUV": 1625, "Pickup": 2200, "Motorcycle": 850 },
  "Toronto": { "end": "Klaipeda", "Car": 900, "SUV": 900, "Pickup": 1200, "Motorcycle": 425 },
  "Honolulu": { "end": "Klaipeda", "Car": 2250, "SUV": 2250, "Pickup": 3000, "Motorcycle": 1450 },
  "Anchorage": { "end": "Klaipeda", "Car": 3300, "SUV": 3300, "Pickup": 3850, "Motorcycle": 1500 }
};

const complexRates = {
  "Klaipeda": [
    { "name": "KLAIPEDA Зимна Вода Львів обл.", "price": 1200 }
  ]
};
